name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.2
    steps:
      - uses: actions/checkout@v4

      - name: Allow Git inside container
        shell: bash
        run: git config --global --add safe.directory /__w/esp-gateway/esp-gateway

      - name: Pin Python deps for idf-component-manager
        shell: bash
        run: |
          python -m pip install --upgrade "pydantic-settings<2.10" "pydantic<2.11"

      - name: Set target
        working-directory: examples
        shell: bash
        run: source ${IDF_PATH}/export.sh && idf.py set-target esp32

      - name: Build
        working-directory: examples
        shell: bash
        run: source ${IDF_PATH}/export.sh && idf.py build
